prjPicoyPlaca/Models/InputsPicoyPlaca.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace prjPicoyPlaca.Models
{
    public class InputsPicoyPlaca
    {
        [Display(Name = "Plate Number:", AutoGenerateFilter = false)]
        [Required(ErrorMessage = "Please, fill the information required.")]
        [StringLength(4, MinimumLength = 4, ErrorMessage = "Please, provide a valid Plate Number.")]
        [RegularExpression(@"^[0-9]{0,9}$", ErrorMessage = "The entry must be numeric characters only.")]
        public string plateNumber { get; set; }

        [Display(Name = "Date:", AutoGenerateFilter = false)]
        [Required(ErrorMessage = "Please, fill out the information required.")]
        public string date { get; set; }

        [Display(Name = "Time:", AutoGenerateFilter = false)]
        [Required(ErrorMessage = "Please, fill the information required.")]
        [DisplayFormat(ApplyFormatInEditMode = true, DataFormatString = "{0:HH:mm}")]
        [DataType(DataType.Time)]
        public TimeSpan time { get; set; }
    }
}

prjPicoyPlaca/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace prjPicoyPlaca.Controllers
{
    public class HomeController : Controller
    {

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }
    }
}

prjPicoyPlaca/Controllers/PicoyPlacaController.cs
using prjPicoyPlaca.Models;
using System;
using System.Collections.Generic;
using System.Globalization;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace prjPicoyPlaca.Controllers
{
    public class PicoyPlacaController : Controller
    {
        public Dictionary<int, string> plateDays = new Dictionary<int, string>() {

            {1, "Monday"}, {2, "Monday"},
            {3, "Tuesday"}, {4, "Tuesday"},
            {5, "Wednesday"}, {6, "Wednesday"},
            {7, "Thursday"}, {8, "Thursday"},
            {9, "Friday"}, {0, "Friday"}
        };

        public TimeSpan restriction_1;
        public TimeSpan restriction_2;
        public TimeSpan restriction_3;
        public TimeSpan restriction_4;

        // GET: PicoyPlaca
        public ActionResult PicoyPlacaVerifier()
        {
            return View();
        }

        [HttpPost]
        public ActionResult PicoyPlacaVerifier(InputsPicoyPlaca inputsPicoYPlaca)
        {
            //Try catch Error Handler
            try
            {
                //Convert string to Datetime the date provided by the user 
                DateTime dayPicked = DateTime.ParseExact(inputsPicoYPlaca.date, "yyyy-MM-dd", CultureInfo.InvariantCulture);

                //Set the Hours of Pico y Placa
                SetHoursPicoyPlaca();

                //Method to verify if the inputs are correct 
                if (InputsValidation(inputsPicoYPlaca.plateNumber, dayPicked))
                {
                    //Retrieve last digit of the Plate provided
                    int numberToVerify = int.Parse(
                                                    inputsPicoYPlaca.plateNumber
                                                    .Substring(inputsPicoYPlaca.plateNumber.Length - 1)
                                                   );
                    //Retrieve the day of the week that the last digit correspond
                    string dayOfWeekPlate = plateDays
                                                .Where(x => x.Key == numberToVerify)
                                                .Select(x => x.Value)
                                                .FirstOrDefault();

                    //Method to validate if the Plate is able to be on road or not.
                    bool response = MainValidationPlate(dayOfWeekPlate, dayPicked, inputsPicoYPlaca.time);

                    if (response)
                    {
                        ViewBag.Message = "You are able to road with the inputs provided.";
                        return View();
                    }
                    else
                    {
                        ViewBag.Message = "You are not able to road with the inputs provided.";
                        return View();
                    }
                }
                else
                {
                    ViewBag.Message = "Please, provide a valid Plate Number or Date.";
                    return View();
                }
            }
            catch
            {
                ViewBag.Message = "Something went wrong. Please, try again later!";
                return View();
            }
        }

        public void SetHoursPicoyPlaca()
        {
            //Hours of restriction expressed on hours, minutes and seconds.
            restriction_1 = new TimeSpan(7, 0, 0);
            restriction_2 = new TimeSpan(9, 30, 0);
            restriction_3 = new TimeSpan(16, 0, 0);
            restriction_4 = new TimeSpan(19, 30, 0);
        }

        public bool InputsValidation(string plateNumber, DateTime dayPicked)
        {
            //Try catch Error Handler
            try
            {
                DateTime today = DateTime.Today;

                //Validation of invalid Plate Number. If the plate number is invalid, it won't validate anything else.
                if (plateNumber.Equals("0000"))
                {
                    return false;
                }

                //Validation of invalid Date (Dates above today's date)
                if (dayPicked.Date >= today)
                {
                    return true;
                }
                else
                {
                    return false;
                }
            }
            catch
            {
                return false;
            }
        }

        //Main Method to Verify if the car can be on road
        public bool MainValidationPlate(string dayOfWeekPlate, DateTime dateProvided, TimeSpan timeProvided)
        {
            //Try catch Error Handler
            try
            {
                //Obtain the Name of the Day received as input
                string dayPicked = dateProvided.DayOfWeek.ToString();
                
                //Verify if the date selected by the user is the same day of the restriction of the Plate
                if (dayPicked != dayOfWeekPlate)
                {
                    return true;
                }
                else
                {
                    //If the time provided by the user is between the restriction of the Day it will return that the car cannot be on road, otherwise it will be able to be on road
                    if ((timeProvided >= restriction_1 && timeProvided <= restriction_2) || (timeProvided >= restriction_3 && timeProvided <= restriction_4))
                    {
                        return false;
                    }
                    else
                    {
                        return true;
                    }
                }
            }
            catch
            {
                return false;
            }
        }

    }
}

prjPicoyPlaca/Views/Home/About.cshtml
@{
    ViewBag.Title = "About Page";
}
<h2>@ViewBag.Title.</h2>

<p>This program provides through the plate number, date and time if a car can be on the road or not.</p>
<hr />
<h3>Important details:</h3>
<hr />
<h5>This program considers the past hours of Pico & Placa: 7:00 - 9:30 and 16:00 - 19:30 </h5>
<h5>The input <b>Plate Number</b> receives a 4 digit number</h5>
<h5>The input <b>Date</b> receives dates above today's date </h5>
<h5>The input <b>Time</b> receives the exact time the user want to know about Pico y Placa </h5>

prjPicoyPlaca/Views/PicoyPlaca/PicoYPlacaVerifier.cshtml
@model prjPicoyPlaca.Models.InputsPicoyPlaca

@{
    ViewBag.Title = "PicoYPlacaVerifier";
}

<h2>Pico Y Placa Verifier</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Detail: This validator provides through the inputs if the car can be on the road or not.</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.plateNumber, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.plateNumber, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.plateNumber, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.date, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.date, new { htmlAttributes = new { @class = "form-control datefield", type = "date" } })
                @Html.ValidationMessageFor(model => model.date, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.time, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.time, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.time, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Verify" class="btn btn-primary" />
            </div>
        </div>
    </div>
}

@if (ViewBag.Message != null)
{
    <script type="text/javascript">

            window.onload = function () {
                alert("@ViewBag.Message");
            };
    </script>

}

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

prjPicoyPlaca/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Pico y Placa Application", "PicoYPlacaVerifier", "PicoyPlaca", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("About", "About", "Home")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
    </div>
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>